services:

  hermes-db:
    image: postgres:15
    restart: always
    container_name: hermes_db
    env_file:
      - .env
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${SUPER_USER_PASSWORD}
    volumes:
      - ./db/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data: